services:
  frontend-service:
    container_name: frontend-container
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-service
    

  backend-service:
    container_name: backend-container
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .:/app
      - E:/documents_uploaded:/app/storage/docs
    
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
    name: IA_JJ_postgres-data